// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFCAPQkHjO73doAzrOP10ePeYcOJunj8E',
    appId: '1:908354481632:web:f5895d48be3c8fa8c30f85',
    messagingSenderId: '908354481632',
    projectId: 'mac-solutions',
    authDomain: 'mac-solutions.firebaseapp.com',
    databaseURL: 'https://mac-solutions-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mac-solutions.firebasestorage.app',
    measurementId: 'G-45GTVS4TGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHoa612_zzy9cdGC3N6HE-94TfC6Zg4kQ',
    appId: '1:908354481632:android:5cd670ed879fb27ac30f85',
    messagingSenderId: '908354481632',
    projectId: 'mac-solutions',
    databaseURL: 'https://mac-solutions-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mac-solutions.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKdnnL3suhBsUh_b8z_eitX7x19r0WPCY',
    appId: '1:908354481632:ios:296d0a92c7d54999c30f85',
    messagingSenderId: '908354481632',
    projectId: 'mac-solutions',
    databaseURL: 'https://mac-solutions-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mac-solutions.firebasestorage.app',
    iosBundleId: 'com.example.inventoryappflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKdnnL3suhBsUh_b8z_eitX7x19r0WPCY',
    appId: '1:908354481632:ios:296d0a92c7d54999c30f85',
    messagingSenderId: '908354481632',
    projectId: 'mac-solutions',
    databaseURL: 'https://mac-solutions-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mac-solutions.firebasestorage.app',
    iosBundleId: 'com.example.inventoryappflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFCAPQkHjO73doAzrOP10ePeYcOJunj8E',
    appId: '1:908354481632:web:6addc185945f3c98c30f85',
    messagingSenderId: '908354481632',
    projectId: 'mac-solutions',
    authDomain: 'mac-solutions.firebaseapp.com',
    databaseURL: 'https://mac-solutions-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mac-solutions.firebasestorage.app',
    measurementId: 'G-R11WT757T1',
  );
}
